name: SwiftLint

on:
  push:
  pull_request:
    branches:
      - develop

jobs:
  check-push:
    if: github.event_name == 'push'
    name: check-push
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install SwiftLint
        run: brew install swiftlint

      - name: Run SwiftLint
        run: swiftlint

  check-pr:
    if: github.event_name == 'pull_request'
    name: check-pr
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install SwiftLint
        run: brew install swiftlint

      - name: Run SwiftLint
        run: swiftlint
        